[package]
name = "srf-n-trf"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
eyre = "0.6.12"
itertools = "0.14.0"
log = "0.4.27"
ordered-float = "5.0.0"
paf = "0.2.1"
rust-lapper = "1.2.0"
